// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// com_expect_cpp
double com_expect_cpp(double lambda, double nu, double rel_tol, int max_iter);
RcppExport SEXP _flexCountReg_com_expect_cpp(SEXP lambdaSEXP, SEXP nuSEXP, SEXP rel_tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(com_expect_cpp(lambda, nu, rel_tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// find_lambda_cpp
double find_lambda_cpp(double mu, double nu, double tol, int max_iter);
RcppExport SEXP _flexCountReg_find_lambda_cpp(SEXP muSEXP, SEXP nuSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(find_lambda_cpp(mu, nu, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// find_lambda_vec_cpp
NumericVector find_lambda_vec_cpp(NumericVector mu, NumericVector nu, double tol, int max_iter);
RcppExport SEXP _flexCountReg_find_lambda_vec_cpp(SEXP muSEXP, SEXP nuSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(find_lambda_vec_cpp(mu, nu, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// cmp_normalizer_vec_cpp
NumericVector cmp_normalizer_vec_cpp(NumericVector lambda_vec, NumericVector nu_vec, double rel_tol, int max_iter);
RcppExport SEXP _flexCountReg_cmp_normalizer_vec_cpp(SEXP lambda_vecSEXP, SEXP nu_vecSEXP, SEXP rel_tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lambda_vec(lambda_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu_vec(nu_vecSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(cmp_normalizer_vec_cpp(lambda_vec, nu_vec, rel_tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// dcom_vec_cpp
NumericVector dcom_vec_cpp(IntegerVector x_vec, NumericVector lambda_values, NumericVector nu_vec, bool log_prob);
RcppExport SEXP _flexCountReg_dcom_vec_cpp(SEXP x_vecSEXP, SEXP lambda_valuesSEXP, SEXP nu_vecSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda_values(lambda_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu_vec(nu_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(dcom_vec_cpp(x_vec, lambda_values, nu_vec, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// pcom_vec_cpp
NumericVector pcom_vec_cpp(IntegerVector q_vec, NumericVector lambda_values, NumericVector nu_vec, bool lower_tail, bool log_p);
RcppExport SEXP _flexCountReg_pcom_vec_cpp(SEXP q_vecSEXP, SEXP lambda_valuesSEXP, SEXP nu_vecSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type q_vec(q_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda_values(lambda_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu_vec(nu_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(pcom_vec_cpp(q_vec, lambda_values, nu_vec, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// qcom_vec_cpp
NumericVector qcom_vec_cpp(NumericVector p_vec, NumericVector lambda_values, NumericVector nu_vec);
RcppExport SEXP _flexCountReg_qcom_vec_cpp(SEXP p_vecSEXP, SEXP lambda_valuesSEXP, SEXP nu_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p_vec(p_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda_values(lambda_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu_vec(nu_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(qcom_vec_cpp(p_vec, lambda_values, nu_vec));
    return rcpp_result_gen;
END_RCPP
}
// rcom_cpp
NumericVector rcom_cpp(int n, double lambda, double nu);
RcppExport SEXP _flexCountReg_rcom_cpp(SEXP nSEXP, SEXP lambdaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(rcom_cpp(n, lambda, nu));
    return rcpp_result_gen;
END_RCPP
}
// dplind_cpp
double dplind_cpp(int x, double mean, double theta);
RcppExport SEXP _flexCountReg_dplind_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(dplind_cpp(x, mean, theta));
    return rcpp_result_gen;
END_RCPP
}
// dplindlogn_cpp
NumericVector dplindlogn_cpp(NumericVector x, NumericVector mean, NumericVector theta, NumericVector sigma, NumericVector h);
RcppExport SEXP _flexCountReg_dplindlogn_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(dplindlogn_cpp(x, mean, theta, sigma, h));
    return rcpp_result_gen;
END_RCPP
}
// dpLnorm_cpp
NumericVector dpLnorm_cpp(NumericVector x, NumericVector mean, NumericVector sigma, NumericVector h);
RcppExport SEXP _flexCountReg_dpLnorm_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(dpLnorm_cpp(x, mean, sigma, h));
    return rcpp_result_gen;
END_RCPP
}
// dpWeib_cpp
NumericVector dpWeib_cpp(NumericVector x, NumericVector mean, NumericVector alpha, NumericVector sigma, NumericVector h);
RcppExport SEXP _flexCountReg_dpWeib_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP alphaSEXP, SEXP sigmaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(dpWeib_cpp(x, mean, alpha, sigma, h));
    return rcpp_result_gen;
END_RCPP
}
// genWaring_cpp
NumericVector genWaring_cpp(NumericVector x, NumericVector mean, NumericVector k, NumericVector p);
RcppExport SEXP _flexCountReg_genWaring_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP kSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(genWaring_cpp(x, mean, k, p));
    return rcpp_result_gen;
END_RCPP
}
// get_chol_cpp
NumericMatrix get_chol_cpp(NumericVector pars, int Nvars);
RcppExport SEXP _flexCountReg_get_chol_cpp(SEXP parsSEXP, SEXP NvarsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< int >::type Nvars(NvarsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_chol_cpp(pars, Nvars));
    return rcpp_result_gen;
END_RCPP
}
// dtri_cpp
double dtri_cpp(double x, double mode, double sigma, double upper, double lower, bool log);
RcppExport SEXP _flexCountReg_dtri_cpp(SEXP xSEXP, SEXP modeSEXP, SEXP sigmaSEXP, SEXP upperSEXP, SEXP lowerSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dtri_cpp(x, mode, sigma, upper, lower, log));
    return rcpp_result_gen;
END_RCPP
}
// ptri_cpp
double ptri_cpp(double q, double mode, double sigma, double upper, double lower, bool lower_tail, bool log_p);
RcppExport SEXP _flexCountReg_ptri_cpp(SEXP qSEXP, SEXP modeSEXP, SEXP sigmaSEXP, SEXP upperSEXP, SEXP lowerSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(ptri_cpp(q, mode, sigma, upper, lower, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// qtri_cpp
double qtri_cpp(double p, double mode, double sigma, double upper, double lower);
RcppExport SEXP _flexCountReg_qtri_cpp(SEXP pSEXP, SEXP modeSEXP, SEXP sigmaSEXP, SEXP upperSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    rcpp_result_gen = Rcpp::wrap(qtri_cpp(p, mode, sigma, upper, lower));
    return rcpp_result_gen;
END_RCPP
}
// rtri_cpp
Rcpp::NumericVector rtri_cpp(int n, double mode, double sigma, double upper, double lower);
RcppExport SEXP _flexCountReg_rtri_cpp(SEXP nSEXP, SEXP modeSEXP, SEXP sigmaSEXP, SEXP upperSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    rcpp_result_gen = Rcpp::wrap(rtri_cpp(n, mode, sigma, upper, lower));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flexCountReg_com_expect_cpp", (DL_FUNC) &_flexCountReg_com_expect_cpp, 4},
    {"_flexCountReg_find_lambda_cpp", (DL_FUNC) &_flexCountReg_find_lambda_cpp, 4},
    {"_flexCountReg_find_lambda_vec_cpp", (DL_FUNC) &_flexCountReg_find_lambda_vec_cpp, 4},
    {"_flexCountReg_cmp_normalizer_vec_cpp", (DL_FUNC) &_flexCountReg_cmp_normalizer_vec_cpp, 4},
    {"_flexCountReg_dcom_vec_cpp", (DL_FUNC) &_flexCountReg_dcom_vec_cpp, 4},
    {"_flexCountReg_pcom_vec_cpp", (DL_FUNC) &_flexCountReg_pcom_vec_cpp, 5},
    {"_flexCountReg_qcom_vec_cpp", (DL_FUNC) &_flexCountReg_qcom_vec_cpp, 3},
    {"_flexCountReg_rcom_cpp", (DL_FUNC) &_flexCountReg_rcom_cpp, 3},
    {"_flexCountReg_dplind_cpp", (DL_FUNC) &_flexCountReg_dplind_cpp, 3},
    {"_flexCountReg_dplindlogn_cpp", (DL_FUNC) &_flexCountReg_dplindlogn_cpp, 5},
    {"_flexCountReg_dpLnorm_cpp", (DL_FUNC) &_flexCountReg_dpLnorm_cpp, 4},
    {"_flexCountReg_dpWeib_cpp", (DL_FUNC) &_flexCountReg_dpWeib_cpp, 5},
    {"_flexCountReg_genWaring_cpp", (DL_FUNC) &_flexCountReg_genWaring_cpp, 4},
    {"_flexCountReg_get_chol_cpp", (DL_FUNC) &_flexCountReg_get_chol_cpp, 2},
    {"_flexCountReg_dtri_cpp", (DL_FUNC) &_flexCountReg_dtri_cpp, 6},
    {"_flexCountReg_ptri_cpp", (DL_FUNC) &_flexCountReg_ptri_cpp, 7},
    {"_flexCountReg_qtri_cpp", (DL_FUNC) &_flexCountReg_qtri_cpp, 5},
    {"_flexCountReg_rtri_cpp", (DL_FUNC) &_flexCountReg_rtri_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_flexCountReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
