# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmp_normalizer_cpp <- function(lambda, nu, maxval = 1000L) {
    .Call('_flexCountReg_cmp_normalizer_cpp', PACKAGE = 'flexCountReg', lambda, nu, maxval)
}

com_expect_cpp <- function(lambda, nu, maxval = 1000L) {
    .Call('_flexCountReg_com_expect_cpp', PACKAGE = 'flexCountReg', lambda, nu, maxval)
}

com_var_cpp <- function(lambda, nu, maxval = 1000L) {
    .Call('_flexCountReg_com_var_cpp', PACKAGE = 'flexCountReg', lambda, nu, maxval)
}

dplind_cpp <- function(x, mean, theta) {
    .Call('_flexCountReg_dplind_cpp', PACKAGE = 'flexCountReg', x, mean, theta)
}

dplindlogn_cpp <- function(x, mean, theta, sigma, h) {
    .Call('_flexCountReg_dplindlogn_cpp', PACKAGE = 'flexCountReg', x, mean, theta, sigma, h)
}

dpLnorm_cpp <- function(x, mean, sigma, h) {
    .Call('_flexCountReg_dpLnorm_cpp', PACKAGE = 'flexCountReg', x, mean, sigma, h)
}

dpWeib_cpp <- function(x, mean, alpha, sigma, h) {
    .Call('_flexCountReg_dpWeib_cpp', PACKAGE = 'flexCountReg', x, mean, alpha, sigma, h)
}

genWaring_cpp <- function(x, mean, k, p) {
    .Call('_flexCountReg_genWaring_cpp', PACKAGE = 'flexCountReg', x, mean, k, p)
}

get_chol_cpp <- function(pars, Nvars) {
    .Call('_flexCountReg_get_chol_cpp', PACKAGE = 'flexCountReg', pars, Nvars)
}

dplindgamma_cpp <- function(x, mean, theta, alpha, h) {
    .Call('_flexCountReg_dplindgamma_cpp', PACKAGE = 'flexCountReg', x, mean, theta, alpha, h)
}

pollind_i_group <- function(mu, y, theta) {
    .Call('_flexCountReg_pollind_i_group', PACKAGE = 'flexCountReg', mu, y, theta)
}

reg_run_RE <- function(beta, y, X, group, weights) {
    .Call('_flexCountReg_reg_run_RE', PACKAGE = 'flexCountReg', beta, y, X, group, weights)
}

