# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

com_expect_cpp <- function(lambda, nu, rel_tol = 1e-10, max_iter = 1000L) {
    .Call('_flexCountReg_com_expect_cpp', PACKAGE = 'flexCountReg', lambda, nu, rel_tol, max_iter)
}

find_lambda_cpp <- function(mu, nu, tol = 1e-8, max_iter = 1000L) {
    .Call('_flexCountReg_find_lambda_cpp', PACKAGE = 'flexCountReg', mu, nu, tol, max_iter)
}

find_lambda_vec_cpp <- function(mu, nu, tol = 1e-8, max_iter = 1000L) {
    .Call('_flexCountReg_find_lambda_vec_cpp', PACKAGE = 'flexCountReg', mu, nu, tol, max_iter)
}

cmp_normalizer_vec_cpp <- function(lambda_vec, nu_vec, rel_tol = 1e-8, max_iter = 1000L) {
    .Call('_flexCountReg_cmp_normalizer_vec_cpp', PACKAGE = 'flexCountReg', lambda_vec, nu_vec, rel_tol, max_iter)
}

dcom_vec_cpp <- function(x_vec, lambda_values, nu_vec, log_prob = FALSE) {
    .Call('_flexCountReg_dcom_vec_cpp', PACKAGE = 'flexCountReg', x_vec, lambda_values, nu_vec, log_prob)
}

pcom_vec_cpp <- function(q_vec, lambda_values, nu_vec, lower_tail = TRUE, log_p = FALSE) {
    .Call('_flexCountReg_pcom_vec_cpp', PACKAGE = 'flexCountReg', q_vec, lambda_values, nu_vec, lower_tail, log_p)
}

qcom_vec_cpp <- function(p_vec, lambda_values, nu_vec) {
    .Call('_flexCountReg_qcom_vec_cpp', PACKAGE = 'flexCountReg', p_vec, lambda_values, nu_vec)
}

rcom_cpp <- function(n, lambda, nu) {
    .Call('_flexCountReg_rcom_cpp', PACKAGE = 'flexCountReg', n, lambda, nu)
}

dplind_cpp <- function(x, mean, theta) {
    .Call('_flexCountReg_dplind_cpp', PACKAGE = 'flexCountReg', x, mean, theta)
}

dplindlogn_cpp <- function(x, mean, theta, sigma, h) {
    .Call('_flexCountReg_dplindlogn_cpp', PACKAGE = 'flexCountReg', x, mean, theta, sigma, h)
}

dpLnorm_cpp <- function(x, mean, sigma, h) {
    .Call('_flexCountReg_dpLnorm_cpp', PACKAGE = 'flexCountReg', x, mean, sigma, h)
}

dpWeib_cpp <- function(x, mean, alpha, sigma, h) {
    .Call('_flexCountReg_dpWeib_cpp', PACKAGE = 'flexCountReg', x, mean, alpha, sigma, h)
}

genWaring_cpp <- function(x, mean, k, p) {
    .Call('_flexCountReg_genWaring_cpp', PACKAGE = 'flexCountReg', x, mean, k, p)
}

dtri_cpp <- function(x, mode = 0, sigma = 1, upper = NA_real_, lower = NA_real_, log = FALSE) {
    .Call('_flexCountReg_dtri_cpp', PACKAGE = 'flexCountReg', x, mode, sigma, upper, lower, log)
}

ptri_cpp <- function(q, mode = 0, sigma = 1, upper = NA_real_, lower = NA_real_, lower_tail = TRUE, log_p = FALSE) {
    .Call('_flexCountReg_ptri_cpp', PACKAGE = 'flexCountReg', q, mode, sigma, upper, lower, lower_tail, log_p)
}

qtri_cpp <- function(p, mode = 0, sigma = 1, upper = NA_real_, lower = NA_real_) {
    .Call('_flexCountReg_qtri_cpp', PACKAGE = 'flexCountReg', p, mode, sigma, upper, lower)
}

rtri_cpp <- function(n, mode = 0, sigma = 1, upper = NA_real_, lower = NA_real_) {
    .Call('_flexCountReg_rtri_cpp', PACKAGE = 'flexCountReg', n, mode, sigma, upper, lower)
}

